 /******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the ULTRASONIC driver
 *
 * Author: Beshoy Ashraf
 *
 *******************************************************************************/
#include "icu.h"
#include "gpio.h"
#include "ultrasonic.h"
#include "util/delay.h"

/*******************************************************************************
 *                            GLOBAL VARIABLES                                 *
 *******************************************************************************/
/* Pulse time */
static volatile uint16 g_high_time=0;
/* Counter */
static volatile uint8 g_ticks=0;


/*******************************************************************************
 *                         Functions Definitions                                *
 *******************************************************************************/
/*
 * Description : Function to initialize the Ultrasonic
 * 	1. Start ICU module:
 * 	 Set the required edge detection.
 * 	 Enable the Input Capture Interrupt.
 * 	 Initialize Timer1 Registers
 * 	2. Setup pins used for trigger and echo in MC.
 */
void Ultrasonic_init(void){
	/* Initializing ICU module to start */
	Icu_ConfigType s_config={F_CPU_8,RISING};
	Icu_init(&s_config);
	Icu_setCallBack(Ultrasonic_edgeProcessing);

    /* Setting direction of trigger pin and echo pin in MC */
    GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,PIN_OUTPUT);
    GPIO_setupPinDirection(ULTRASONIC_ECHO_PORT_ID,ULTRASONIC_ECHO_PIN_ID,PIN_INPUT);
}



/*
 * Description :
 *  Function to send Trigger pulse to Ultra-sonic:
 *  by writing logic high- delay- logic low to the trigger pin.
 */
void Ultrasonic_Trigger(void){
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_us(15);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_LOW);
}



/*
 * Description :
 *  Function to calculate distance of object away from Ultrasonic sensor:
 *  Uses Ultrasonic_Trigger() function to send signal.
 *  Uses g_high_time calculated by Ultrasonic_edgeProcessing() function.
 *  Then calculates the total distance by the eqn (g_high_time) / 58.8.
 */
uint16 Ultrasonic_readDistance(void){
	Ultrasonic_Trigger();
	return (uint16)(((float)g_high_time/58.7)+1);
}



/*
 * Description :
 *  Function to calculate high time (pulse) generated by Ultrasonic sensor:
 */
void Ultrasonic_edgeProcessing(void){
	g_ticks++;
	if (g_ticks==1)
	{
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(FALLING);
	}
	else if (g_ticks==2)
	{
		g_high_time=Icu_getInputCaptureValue();
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(RISING);
		g_ticks=0;
	}
}
